### ISSUE TITLE
Divesting amount close to your bankroll returns incorrect error

### ISSUE THREAD

**Issue by DarkStarFTW** [bustabit/bustabit-client#68]
I tried to divest 93000 bits (my BR was 93375 bits according to the site), but it gives an error stating that a game is running, when it isn't.

http://i.imgur.com/MGCGde1.gifv

**Comment by DarkStarFTW** [comment]
Divesting a smaller amount works (like 90k bits)

**Comment by RHavar** [comment]
There's actually two different states, "GAME_ENDED" and "GAME_STARTING". The GAME_ENDED state is when it shows "Game busted"  and "GAME_STARTING" is when it allows new bets. In the gif you were trying to invest when the game was in GAME_STARTING while because it means players are currently betting the server won't accept investments.

Anyway, the whole thing sucked and was confusing. And now it's been fixed, it'll queue your investment until the game goes into GAME_ENDED and send your invest/divest, should be a lot easier to use
